
# Dictionary: key = abbreviation, value = list of possible full names
replace_dict = {
"Department of Science and Technology": 
        ["DST","Indian Association for the Cultivation of Science", 
        "Indian Association of Cultivation of Science",'IACS',
        "Indian Association for Cultivation of Science",
        "ARCI","Anusandhan National Research Foundation","ANRF",
        "Teacher Associateship for Research Excellence",
        "National Postdoctoral Fellowship","SCTIMST","I-HUB Quantum",
        'CENS',"Birbal Sahni Institute of Palaeosciences","Indian Institute of Astrophysics",
        "Technology Systems Development Program","Indian Solar Energy Harnessing Center",
        'JNCASR', 'Jawaharlal Nehru Centre for Advanced Scientific Research',"Sheik Saqr",
        "Sheikh Saqr","International Centre for Materials Science","ICMS",
        "Department of Science (India)","R&D Project of the Ministry of Science and Innovation",
        "School of Advanced Materials","Department of sciene and technology",
        "Dept. of science & Technology, New Delhi, India",
        'Dept. of Science and Technology','INSPIRE',"MATRICS","CCSTDS",
        "S. N. Bose National Centre for Basic Sciences","SNBNCBS","Bose Centre",
        "S N Bose National Centre for Basic Sciences","Bose National Centre",
        "National Centre for Basic Sciences, Kolkata, India, for the DLS measurements",
        "Women Scientist Scheme", "WISE KIRAN","Women Scientists Scheme","Women Scientists",
        "Women Scientist-A fellowship","Centre for Fuel Cell Technology",
        "National Centre for Basic Sciences, India",'IASST',
        "Institute of Advanced Study in Science and Technology",'FIST',
        "TIFAC","NECTAR","national innovation foundation",
        "Institute of Nano Science and Technology","INST, Mohali","SPLICE",
        "Centre for Nano and Soft Matter Sciences","Mission on Nano Science",
        "Department of Science & Technology", "Department of Science and Technology",
        "Dept. of Science & Technology, New Delhi, India",
        "Department of Science Technology","the Department of Science Technology",
        "Science & Technology (S & T) Department, Govt.",
        'Department of Science and Technology, India',
        'Department of Science, India',
        'Department of Sciences and Technology, Delhi, India',
        'Department of Science & Technology, India',
        'Depat Intent Science and Technology, India',
        'Depatment of Science and Technology, India,'
        'Departmen of Science and Technology, New Delhi, India'
        'Department Science and Technology, India',
        'New Delhi, India, Science and Technology Department',
        'New Delhi, India, S & T Department Project',
        'Science and Technology, India',
        'Science and Technology India',
        'Departmenof Science and Technology, India',
        'Deparatment of Science and Technology, New Delhi, India',
        'Indian Department of Science amp', "Science & Engineering Research Board",
        'PURSE',"SERB",'Science and Engineering Research Board',"National Science Chair", 
        "Mathematical Research Impact Centric Support Grant",
        "Empowerment and Equity Opportunities","Equity Opportunities for Excellence in Science",
        'The science and Engineering Research Board','Science and Engineering Board',"SUPRA",
        "Sir J. C. Bose Fellowship, India","Bose National Fellowship",
        "J. C. Bose Fellowship, New Delhi, India","Bose Fellowship",
        "Early Career Research Award","National Post-doctoral Fellowship",
        "National Post Doctoral Fellowship","Nano Mission",
        "SAIF","SATYAM","Swarnajayanti","Swarna Jayanti Fellowship","NSTMIS","VAJRA",
        "ICPS","Natural Resources Data Management System","NCSTC",
        "Fast Track Scheme for Young Scientist",
        "National Super computing Mission","National Supercomputer Mission",
        "National Super-computing Mission (NSM), India",
        "National Supercomputing Mission","Drug and Pharmaceuticals Research Programme",
        "Ramanujan","INAE","Kalam National Innovation fellowship",
        "Fulbright-Kalam","STEMM", "CEFIPRA","LAFICS",
        "Indo-French Centre for the Promotion of Advanced Research","IFCPAR",
        "Indo-French Centre for Advanced Scientific Research","Indo-french",
        "French-Indian UCA project", "I-STEM","Clean Coal Technology Project",
        "Aryabhatta Research Institute of Observational Sciences","ARIES",
        "Indian Science Congress Association","Indian Astronomical Observatory",
        "National Innovation Foundation, India","National Innovation Foundation-India",
        "NIF, India","Abdul Kalam Technology Innovation",
        "Drug and Pharmaceuticals Research Programe (DPRP)","Bose Institute"
        ],

"Council of Scientific and Industrial Research":
        ['CSIR','Council of Scientific and Industrial Research','Council of Science and Industrial Research',
         'Council of Industrial and Scientific Research',"Council for Scientific & Industrial Research",
         'Indian Institute of Chemical Biology','NML',"National Metallurgical Laboratory",
         'NISCPR','SERC','IIIM','IITR','IIMT','IMTECH','IMTECH',"Indian Institute of Toxicology Research",
         'National Aerospace Laboratories',"National Aerospace Laboratories",'NBRI','NCL','NEERI',
         "National Chemical Laboratory","National Aerospace Laboratory","Central Leather Research Institute",
         'NEIST','NGRI','National Institue of Oceanography',"National Institute of Oceanography",
         'CCMB','SPMF','Shyama Prasad Mukherjee',"Center of Advanced Study Funds",
         "Council and Scientific and Industrial Research Institute","Council for Scientific and Industrial Research",
         "Industrial Research, India","Industrial Research, New Delhi","Aromatic Plant",
         'Centre for Cellular and Molecular Biology','CECRI','HRDG',
         'CEERI','CFTRI','Central Food Technological Research Institute',
         'CGCRI','CIMAP','CIMFR','CLRI','CMERI','CRRI','CSMCRI',
         "Council of Scientific","New Millennium Indian Technology Leadership Initiative",
         "NMITLI",
         'IGIB','IHBT','IICB','IICT',"Indian Institute of Chemical Technology",'CSIO','CDRI',
         'National Physical Laboratory','Central Scientific and Industrial Research',
         'Shanti Swarup Bhatnagar Prize',"Raman Research Fellowship",
         'AcSIR','Academy of Scientific and Innovative Research',
         "Central Drug Research Institute","Open Source Drug Discovery",
         "Hydrogen Mission Mode Project (H2T mission) - Development of Electrolyser Technology for Affordable Generation of Hydrogen (DELTAGH)",
         'Academy of Scientific & Innovative Research',"Human Resource Development Group"
         ],

"University Grants Commission":
        ["UGC", "University Grants Commission","University Grant Commission",
        "Unversity Grants Commission, New Delhi, India",
        "University of Grant Commission, New Delhi, India",
        "University Grants Commision-India","University Grand Commission",
        "United Grants Commission",           
        "Union Grants Commission, New Delhi, India",
        "University Grant Fellowship India for the University Fellowship",
        "Kothari Postdoctoral Fellowship","DSKPDF", "Kothari Post Doctoral","Kothari’s Post-Doctoral",
        "Special Assistance Program","Potential for Excellence","University Gransts Commission",
        "Junior Research Fellowship","Senior Research Fellowship","Rajiv Gandhi National Fellowship",
        "Inter University Accelerator Centre","Inter University Accelerator Center", 'IUAC','Inter-University Accelerator Centre',
        "IUCAA","InterUniversity Centre for Astronomy and Astrophysics","IUCCA",
        "Inter-University Centre for Astronomy and Astrophysics","Consortium For Scientific Research",
        "University Research Fellowship scheme, Salem, India"],

 "Department of Biotechnology":
        ["Department of Biotechnology","Dept. of Biotechnology",
        "DBT","CDFD","Centre for DNA Fingerprinting and Diagnostics","Dept of Biotechnology",
        "National Brain Research Centre","NBRC","National Brain Research Center",
        "NII, New Delhi","NII core grant","NII Core Fund","NII New Delhi",
        "NII Administration and Finance","NII International Internship Program",
        "National Institute of Immunology","core grant of NII","ICGEB", "MTCC",
        "NABI intramural funds","NABI CORE Research Grant","NABI's","NABI, Mohali, India",
        "National Agri-Food Biotechnology Institute","Regional Centre for Biotechnology",
        "Biotech Science Cluster","InStem","Bangalore Life Science Cluster",
        "Translational Health Science and Technology Institute","CRDF",
        "PARAM Smriti at NABI","National Centre for Cell Science","NCCS","NIAB",
        "National Institute of Biomedical Genomics","NIBMG","Rajiv Gandhi Centre for Biotechnology","RGCB",
        "THSTI", "Biotechnology Industry Research Assistance Council", "BIRAC",
        "Grand Challenges India","Biotechnology Institute (NABI)",
        "NIPGR","National Institute of Plant Genome Research",
        "Punjab Biotechnology Incubator","Advance Level Institutional Biotech Hub","National Biopharma Mission",
        "University Interdisciplinary Life Science Departments for Education and Research","BioCARe",
        "National Bioscience Award","Ramalingaswami","MK Bhan","NBACD","IBSD",
        "National Institute of Animal Biotechnology",
        "Innovative Young Biotechnologist Award","National Bioscience Career Development award",
        "Microbial Culture Collection Project","BTIS-Net-Sub-Distributed Information Centre"
        ],

"Department of Atomic Energy":
        ['Board of Research on Nuclear Science','B.R.N.S',
        "Board of Research in Nuclear Studies",'National Board of Higher Mathematics',
        'National Institute of Science Education and Research',
        'IMSC','Institute for Plasma Research','homi bhabha',
        "Bhabha Atomic Research Center",
        'Board of Research in Nuclear Science','Tata Institute of Fundamental Research',
        'Tata Memorial Centre',"ACTREC","Advanced Centre for Treatment Research and Education",
        "Institute of Nanoscience and Technology",
        "National Cancer Grid","Centre for Excellence in Basic Sciences",
        "Board of Research Nuclear Sciences",
        'NISER',"Saha Institute of Nuclear Physics",
        'SINP',"DAE",'Bhabha Atomic Research Centre','BARC',
        "IGCAR","Indira Gandhi Centre for Atomic Research",
        "RRCAT","Raja Ramanna Centre for Advanced Technology",
        "VECC","Variable Energy Cyclotron Centre",
        "Nuclear Fuel Complex","Board of Radiation and Isotope Technology",
        "NPCI", "KSKRA", "Raja Ramanna",
        'National Board for Higher Mathematics','NBHM',
        'Dept. of Atomic Energy', "Department of Atomic Energy",
        'National Centre for Biological Sciences',"National Center for Biological Sciences",
        'NCBS','Harish-Chandra Research Institute',
        "RECAPP","Bhaskaracharya Pratisthana",
        "Tata Institute of Fundamental Re-search","Tata Institute for Fundamental Research",
        "BRNS",'TIFR',"National Analytical Facility for Nutrition Metabolism",
        'ICTS','HBNI','Institute of Mathematical Sciences',"Atomic Energy Regulatory Board",
        "AERB"
        ],

"Indian Council of Medical Research":
        ["Department of Health Research",
        "Indian Council of Medical Research","ICMR","Indian Council Medical Research",
        "Indian Medical Research Council","Council of Medical Research",
        "National Institute for Research in Reproductive Health","NIRRCH",
        "National Institute of Virology","Indian Council of Medicinal Research",
        "Indian Council of Medical","VRDL","National Institute of Malaria Research",
        "National Institute of Nutrition","Indian Council of the Medical Research",
        "Indian Council for Medical Research","Indian Cauncil for medical Research"
        ],

"Ministry of Human Resource and Development":
        ["Rashtriya Uchchatar Shiksha Abhiyan",
        'Rashtriya Uchachatar Shiksha Abhiyan','RUSA',
        'Higher Education Financing Agency','HEFA'
        "Ministry of Education (MoE), India","Ministry of Education (MoE) India",
        "Ministry of Human Resource Development","Department of Higher Education, India",
        "Ministry of Human Resource Development, New Delhi",
        "Ministry of Human Resource Development of India",
        "Ministry of Human Resources and Development, India",
        "Ministry of Human Resource Development, Delhi, India",
        "Education Ministry, India","Institute of Eminence",
        "Ministry of Human Resources and Development, New Delhi, India",
        "Ministry of Education, New Delhi","Ministry of Education (MoE), New Delhi",
        "Ministry of Education, GoI","Ministry of Education, India","Ministry of Education (MoE, India)",
        "Ministry of Education, New Delhi, India","Ministry of Education India",
        "Ministry of Education (New Delhi, India)","Indian Ministry of Education",
        "Ministry of education India","Ministry of Education, Gov. of India",
        "MoE (Ministry of Education)","MoE, Govermment of India",
        "Bridge grant","IIEST","Ministry of Higher Education (MoE) , India",
        "Min-istry of Education, India","Ministry of Education (MoE), Delhi, India",
        "Ministry of Education, Governmentof India","Ministry of Education in India",
        "Indian government's ministry of education","Ministry of Education, MoE, India",
        "Ministry of Education, Govt.of India",
        "Ministry of Education (MoE) of India","Ministry of Human Resource Development, India",
        "Ministry of Human Resource, India","Ministry of Human Resources, India",
        "Indian Ministry for Human Resource Development","IMPRINT",
        "Ministry of Human Resource Department, India","Ministry of Human and Resources Development, India",
        'Ministry of education, India','Ministry of Education (India)',
        'Ministry of Education of India','Ministry of Education (MoE) , India',
        'Ministry of Human Resource and Development','Ministry of Human Resources Development',
        'Ministry of Education, India', 'MHRD','Ministry of Education (MoE), India',
        "Prime Minister's Research Fellowships","Prime Minister Research Fellowship","PMRF",
        "Prime Ministre's Research fellowship","TEQIP",
        "Indian Institute of Information Technology",
        "Prime Minister's Fellowship Scheme for Doctoral Research, India",
        "Prime Minister's Research Fellowship","Prime Minister's Research Fellowships",
        "Prime Minister Research Fellowship","Prime Minister's Fellowship",
        "Prime Minister's Re-search Fellowship Scheme, India",
        "Prime Minister's Research Fellow scheme, India",
        "India's prestigious doctoral fellowship program namely Prime Minister's Fellowship",
        "Scheme for Promotion of Academic and Research Collaboration",
        "SPARC","Utchattar Avishkar Yojana","Scheme for Transformational and Advanced Research in Sciences",
        "STARS"
        ],

"Indian Institutes of Technology":
        ["IITGN","IITB","IITM","IITG","IITI","IITK","IITJ","IITKGP","IITH",
        "IITBHU","IITPKD","IITD","IITTP","IITDH",'Indian school of mines',"ISM, Dhanbad",
        "Indian the Institute of Technology Delhi", "Indian Institute of Technolgy",
        "Indian Institute of Tech-nology","Indian Institute ofTechnology",
        "Indian Instituteof Technology","Indian Institute of Technol- ogy",
        "Indian Institute of Technol-ogy","IIT, India","IIT Hyderabad","IRCC, IIT","IRCC-IIT","IIT Patna",
        "IIT Mandi","IIT Bhubaneswar","IIT Jodhpur","IITKanpur","IIT KGP","IITKGP","IITKharagpur","IITBombay",
        "Department of Chemistry, IIT","Indian Institute Technology","NIT Tiruchirappalli",
        'Indian Institute of Technology', 'I.I.T.',"National Facility of Texture",
        "Industrial Research and Consultancy Centre","Society for Innovation and Entrepreneurship",
        "AMOLED Research Center (National Center of Excellence)","Center for NEMS and Nanophotonics (CNNP)",
        "Centre on Ceramics Technologies for the futuristic mobility","Indian Institute of Bombay",
         "Centre for Research and Development of Scientific Instruments",
         "Indian Institution of Technology",
        "National Centre for Combustion Research and Development",
        "Industrial Research and Consultancy Centre","Thematic Unit of Excellence (TUE)",
        "Sponsored Research & Industrial Consultancy Office","Sponsored Research & Industrial Consultancy",
        "Sponsored Research and Industrial","Kohli Center on Intelligent Systems",
        "Centre for 2D Materials Research and Innovation",
        ],

"Indian Council of Agricultural Research":
        ["Indian Council of Agricultural Research","Indian Council of Agricultural Reesearch",
        "Indian Council for Agricultural Research","IIPR",'Indian Council of Agricultural Reseach',
        'Indian Council of Agricultural Sciences','Indian Council of Agriculture and Research',
        "ICAR, New Delhi, India","Indian Council of Agriculture Research",
        "National Agricultural Innovation Project","Central Institute of Fisheries Education",
        "All India Network Project on soil biodiversity and biofertilizers","AICRP",
        "National Agricultural Science Fund","NASF","CICR",
        "Indian Veterinary Research Institute","CADRAD","AICPMIP","AICCIP",
        "Indian Institute of Horticultural Research",
        "IARI","Indian Agricultural Research Institute","Pusa New Delhi",
        "National Institute for Plant Biotechnology",
        "National Dairy Research Institute","NDRI, Karnal","National Dairy Development Board",
        "Central Institute for Research on Goats","CIRB",
        "Central Institute for Cotton Research","Central Institute of Fisheries Technology",
        "Central Plantation Crops Research Institute","Central Potato Research Institute",
        "Central Research Institute for Jute and Allied Fibres","NRRI",
        "Central Soil Salinity Research Institute","IGFRI",
        "Institute of Agricultural Biotechnology","Indian Institute of Soil Science",
        "Indian Institute of Spices Research","Indian Institute of Sugarcane Research",
        "Indian Institute of Vegetable Research","National Institute of Abiotic Stress Management",
        "Sugarcane Breeding Institute","National Institute of High Security Animal Diseases",
        "Indian Institute of Maize Research","Indian Institute of Wheat and Barley Research",
        "Farming System Research","Rice Research, Hyderabad","National Research Centre on Plant Biotechnology"
        "National Research Centre for Banana","National Innovations in Climate Resilient Agriculture",
        "NICRA","National Bureau of Plant Genetic Resources","NBPGR",
        "National Bureau of Agriculturally Important Microorganisms",
        "National Agriculture Innovative Project","National Agricultural Technology Project",
        "NFBSFARA","National Fund for Basic, Strategic and Frontier Application Research in Agriculture",
        "All India Coordinated Research Project (AICRP) on Energy in Agriculture",
        "All India Coordinated Research Project on Agroforestry",
        'All India Coordinated Research Project on Biological Control of Crop Pests',
        'All India Coordinated Research Project on Farm Implements and Machinery',
        'All India Coordinated Research Project on Harvesting, Processing and Value Addition of Natural Resins and Gums',
        'All India Coordinated Research Project on Honey bees and Pollinators',
        'All India Coordinated Research Project on Integrated Farming Systems, Modipuram',
        'All India Coordinated Research Project on Micro- and Secondary Nutrients and Pollutant Elements in Soils and Plants',
        'All India Coordinated Research Project on Sugarcane at various centres',
        'All India Coordinated Research Project on Vertebrate Pest Management',
        'All India Coordinated Rice Improvement Project','All India Network Project on Bluetongue',
        'All India Network Project on Mariculture','All India Network Project on Pesticide Residues, New Delhi',
        'All India Network Project on Pesticides','All India Network Project on Whitegrubs and Other Soil Arthropods',
        'All India Network Programme on Bluetongue','All India Network Programme on Haemorrhagic septicaemia',
        'All India Network Programme on Organic Farming','All India Network Project on Rodent Control',
        ],

"Defence Research and Development Organization":
        ['DRDO',"Defense Research Development Organization, India",
        "Defence Research Develpoment Organisation India","INMAS",
        "Defense Research and Development Organisation",
        "Defence Research and Development Establishment","Defence Research and Development Organisation",
        "Defence Research and Development Laboratory","Defence Research Development Laboratory",
        "Ministry of Defense","Ministry of Defence", "Defence Ministry (R and D) of India",
        "Naval Physical and Oceanographic Laboratory","Defence Research Laboratory",
        "Armament Research Board", "Defence Research and Development Organization",
        "Defence Research & Development Organisation","HEMRL","CFEES",
        "Defence Institute of Advanced Technology","Gas Turbine Research Establishment","GTRE",
        "DRDL","TBRL","LRDE","IRDE","CVRDE","NPOL","NSTL","DIPAS","DMRL","DMSRDE","LASTEC",
        "Naval Research Board","NRB","Life Sciences Research Board",
        "Life Science Research Board","Aeronautics Research and Development Board","LSRB",
        "ARDB","Aeronautical Research and Development Board",
        "DRDE Project Task",     
        ],

"Central Universities":
        ["Aligarh Muslim University","Aligarh","Assam University","Babasaheb Bhimrao Ambedkar University","BBAU",
        "Banaras Hindu University","BHU","Central Agricultural University, Imphal",
        "Punjab Agricultural University","Central University Punjab","Department of Entomology, PAU",
        "Central Agricultural University, Iroisemba, Imphal","CAU (Imphal)","CURAJ",
        "Central University of Gujarat","CUG, Gandhinagar","CIF-CUG","CUG Gandhinagar",
        "Central Instrumentation Facility (CIF), CUG","Central University of Gujarat (CUG), Gandhinagar",
        "Central University of Haryana","Research Develeopment Cell of CUH","Central University of Himachal Pradesh",
        "Central University of Jammu","Central University of Jharkhand","Central University of Karnataka",
        "Central University of Punjab","Central University of Rajasthan","Central University of South Bihar",
        "Central University of Tamil Nadu","Harisingh Gour Vishwavidyalaya",
        "Rajendra Prasad Central Agricultural University","Guru Ghasidas Vishwavidyalaya","GGV",
        "GGV, Bilaspur, India","Hemvati Nandan Bahuguna Garhwal University","Garhwal University",
        "Indira Gandhi National Open University",
        "IGNOU","Jawaharlal Nehru University","JNU","Jawahar Lal Nehru University",
        "Mahatma Gandhi Central University","Jamia Millia Islamia",
        "Manipur University","Mizoram University","North Eastern Hill University","NEHU",
        "Pondicherry University","Rajiv Gandhi University","Sikkim University",
        "South Asian University","SAU, New Delhi","Tezpur University",
        "Indira Gandhi National Tribal University","IGNTU","Tripura University",
        "University of Allahabad","Allahabad University","University of Delhi","Delhi University", 
        "Institute of Home Economics",
        "University of Hyderabad","UOH","Visva-Bharati","Visva Bharati","Visvabharati University",
        ],

"Indian Institute of Science and Indian Institutes of Science Education and Research":
        ["Indian Institute of Science","IISc","Indian Institute Science",
        'IISER','Indian Institute of Science Education and Research',"Indian Institute of Scienc",
        'Indian Institute of Science Education & Research',"Kishore Vaigyanik Protsahan Yojana",
        "KVPY","Center of Excellence in Space Sciences (CESSI)",
        "Indian Institutes of Science Education and Research","Indian Institution of Science Education and Research",
        "Indian Insititute of Science Education and Research"
        ],

"State Universities":
        ["Punjab University", "Acharya N.G.","ANGRAU","S.V. University-Tirupati","Acharya Nagarjuna University",
        "Adikavi Nannaya University","S.V. University","Andhra University", "Dr. B. R. Ambedkar University",
        "Jawaharlal Nehru Technological University","JNTU","Rajiv Gandhi University of Knowledge Technologies",
        "Padmavati Mahila Visvavidyalayam","University of Mumbai",
        "Venkateswara Veterinary University","Venkateswara University","Yogi Vemana University",
        "Assam Agricultural University","Bodoland University","Cotton University","Dibrugarh University",
        "Gauhati University", "Bihar Agricultural University","Magadh University","Patna University",
        "Panjab University","Indira Gandhi Krishi Vishwavidyalaya","Ravishankar Shukla University",
        "Delhi Technological University","Guru Gobind Singh Indraprastha University",
        "Kerala Agricultural University", "Indira Gandhi Delhi Technical University","Netaji Subhas University of Technology",
        "Goa University","Anand Agricultural University","Bhakta Kavi Narsinh Mehta University",
        "Dharmsinh Desai University","Gujarat Biotechnology University","Gujarat Technological University",
        "Gujarat University","MS University Baroda","University of Baroda","Sardar Patel University",
        "Saurashtra University","Chaudhary Bansi Lal University","YMCA","Bose University of Science",
        "Kurukshetra University","CVAS, RAJUVAS, Bikaner","Gujral Punjab Technical University",
        "Lala Lajpat Rai University of Veterinary","M.D. University","Maharshi Dayanand University",
        "MDU Rohtak","MDU, Rohtak","Parmar University of Horticulture","Himachal Pradesh University",
        "HPU Summer Hill, Shimla","Maharishi Dayanand University","MaharshiDayanand University",
        "Kashmir University","University of Kashmir","Centre for Biodiversity and Taxonomy",
        "Shri Mata Vaishno Devi University",
        "Birsa Agricultural University","Vinoba Bhave University","Bangalore University",
        "Davangere University","Gulbarga University","Karnatak University","Karnataka University",
        "K. U. Dharwad","K U Dharwad","KU, Dharwad",
        "Karnataka Veterinary","Kuvempu University","Mangalore University","Centre for Application of Radioisotopes & Radiation Technology",
        "University of Mysore",
        "Rajiv Gandhi University of Health Sciences","Rani Channamma University","Tumkur University",
        "University of Agricultural Sciences","GKVK","University of Horticultural Sciences","VTU","Vijayanagara",
        "Abdul Kalam Technological University","AbdulKalam Technological University",
        "Calicut University","University of Calicut",
        "Cochin University of Science and Technology", "CUSAT","Kannur University","Kerala University",
        "University of Kerala","Kerala Veterinary","Mahatma Gandhi University","Devi Ahilya Vishwavidyalaya",
        "Jawaharlal Nehru Krishi Vishwavidyalaya","Jiwaji University","Vikram University",
        "Babasaheb Ambedkar Marathwada University","Babasaheb Ambed-kar Marathwada University",
        "Ambedkar Marathwada University",
        "Kavayitri Bahinabai Chaudhari North Maharashtra University","Konkan Krishi Vidyapeeth",
        "Maharashtra Animal and Fishery Sciences University","Mahatma Phule Krishi Vidyapeeth",
        "Punyashlok Ahilyadevi Holkar Solapur University","Rashtrasant Tukadoji","Sant Gadge Baba Amravati University",
        "University of Pune","Savitribai Phule Pune University","SPPU","Savitribai Phule Pune Unversity","BCUD",
        "Shivaji University","Swami Ramanand Teerth Marathwada University","SRT Marathwada University",
        "Berhampur University",
        "Fakir Mohan University","Gangadhar Meher University","Odisha University of Agriculture and Technology",
        "Ravenshaw University","Sambalpur University","Utkal University","Veer Surendra Sai University","VSSUT",
        "Guru Nanak Dev University","GNDU", "Maharaja Ranjit Singh Punjab Technical University","MRSPTU",
        "Punjab Agriculture University","Punjabi University","Maharana Pratap University of Agriculture and Technology",
        "Mohanlal Sukhadia University","MLS University",
        "Rajasthan University","University of Rajasthan, Jaipur",
        "Alagappa University","Periyar University","University of Jammu",
        "Bharathiar University",
        "BCTRC","Bharathidasan University",
        "Madurai Kamaraj University","USRF","Anna University","University of Madras","Manonmaniam Sundaranar University",
        "Manonmaniam Sunda-ranar University","Annamalai University","Tamil Nadu Fisheries University",
        "Tamil Nadu Open University","M.G.R. Medical University","Tamilnadu Veterinary and Animal Sciences University",
        "Kakatiya University","Osmania University","Nizam College","Professor Jayashankar Telangana State Agricultural University",
        "Bundelkhand University","Chaudhary Charan Singh University","Chhatrapati Shahu Ji Maharaj University",
        "Gautam Buddha University","Guru Jambheshwar University","Department Of Physics GJU S T Hisar",
        "Madan Mohan Malaviya University of Technology",
        "University of Lucknow","Doon University","Pant University","Kumaun University",
        "Uttarakhand Technical University","Aliah University","University of Burdwan","Burdwan University",
        "Department of Botany, BU, West Bengal, India","Indian Centre for Space Physics",
        "University of Gour Banga","Bidhan Chandra Krishi Viswavidyalaya","University of Calcutta",
        "Calcutta University","CU for the UPE-II Nanofabrication project fund",
        "Centre for Research in Nanoscience and Nanotechnology",
        "Presidency University","University of North Bengal","North Bengal University",
        "Jadavpur University","Kalyani University","University of Kalyani",
        "Kazi Nazrul University","Maulana Abul Kalam Azad University of Technology","MAKAUT","Sidho-Kanho-Birsha University",
        "West Bengal University","Vidyasagar University","West Bengal State University",
        "Raiganj University", 
        ],

"Ministry of Electronics and Information Technology":
        ['MEITY','Ministry of Electronics and Information Technology',
        "Ministry of Electronics & Information Technology",
        "Ministry of Communication and Information Technology",
        'Department of Information Technology','National Informatics Centre',
        "Digital India Corporation","C-DAC","Centre for Development of Advanced Computing",
        "CDAC","C-MET","Centre for Materials for Electronics Technology","CMET",
        "Semiconductor Laboratory", "Ministry of Communications and Information Technology",
        "Ministry of Information Technology, India","YFRF",
        "Centre for Excellence in Nanoelectronics",
        "Visvesvaraya Young Faculty Fellowship","Indian Nanoelectronics Users Program",
        "Ministry of Information and Technology (MIT), India",
        "Department of Electronics and Information Technology",
        "DEITY","Department of Electronics and IT, India",
        ],

"Ministry of Earth Sciences":
        ["Ministry of Earth Sciences","Ministry of Earth Science",
        "Department of Ocean Development",
        "MOES","Ministry of Earth Science, India",
        "Minsitry of Earth Sciences, New Delhi, India",
        "Centre for Marine Living Resources and Ecology",
        "CMLRE","National Centre for Coastal Research",
        "National Centre for Antarctic and Ocean Research",
        "Indian Meteorological Department","India Meteorological Department","IMD, New Delhi",
        "National Centre for Medium Range Weather Forecasting","NCMRWF",
        "National Institute of Ocean Technology","NIOT",
        "National Centre for Polar and Ocean Research", "NCPOR",
        "Indian National Centre for Ocean Information Services","INCOIS",
        "Sustained Indian Ocean Biogeochemical and Ecological Research (SIBER) program",
        "IMBeR (Integrated Marine Biosphere Research) regional program SIBER (Sustained Indian Ocean Biogeo-chemistry and Ecosystem Research)",
        "Indian National Centre for Ocean In-formation Services",
        "Indian Institute of Tropical Meteorology",
        "National Centre for Earth Science Studies"
        ],

"Department of Space (ISRO)":
        ['IIRS','ISTRAC','NRSC',"National Remote Sensing Centre",'Satish Dhawan Space Centre',
        'Indian Space Research Organisation','URSC',"Indian Institute of Remote Sensing",
        'Indian Institute of Space Science and Technology',"Antrix"
        'NARL','Space Applications Centre','Space Application Centre',
        'ISRO','Physical Research Laboratory','Indian Space Research Organization',
        'DoS','Department of Space','Space Application Centre', 'VSSC'
        ],

"National Institutes of Technology":
        ['NITK','NITJ', 'National Institute of Technology','SVNIT','MNIT','MNNIT',
        'NIT Jamshedpur','NIT Warangal','NITW','NIT Silchar','NIT Patna','NIT Calicut',
        "NIT Jalandhar","NIT, Raipur","NIT, Arunachal Pradesh","NIT, Mangalore",
        "Centre for Computational Modelling and Simulation",'NIT Raipur','NIT Delhi',
        "NIT-Rourkela",
        'NIT Hamirpur','NIT Kurukshetra','NIT Srinagar','NIT Jamshedpur','NIT Manipur',
        'NIT Meghalaya','NIT Nagaland','NIT Rourkela','NIT Trichy','NIT Agartala',
        'NIT Uttarakhand','NIT Durgapur','VNIT, Nagpur','VNIT Nagpur',"Department of Physics VNIT",
        'NIT Andhra Pradesh',"Sardar Vallabhbhai National Institute of Technology"        
        ],

"All India Council for Technical Education":
        ["All-India Council for Technical Education","AICTE",
        "All India Council for Technical Education","Council for Technical Education",
        "All India Council of Technical Education","National Doctoral Fellowship"
        ],

"Indian National Science Academy":
        ['Indian National Science Academy','INSA','National Science Academies of India',
        "Indian Nation Science Academy, New Delhi",
        "Indian National Science Acade-my-New Delhi"
        ],

"Government of Kerala":
        ["Government of Kerala","Rajagiri College",
        "Kerala State Council for Science",
        "KSCST&E, Kerala, India","DCE, Kerala, India",
        "Kerala Forest Department, Kerala, India",
        "Post metric Scholarship-Kerala (e-grantz), India",
        "National Centre for Earth Sciences Studies Trivandrum Kerala",
        'KSCSTE',"Govt. of Kerala","Sophisticated Test and Instrumentation Centre",
        "Higher Education Department (Kerala Government)", "Regional Cancer Centre",
        "Regional Cancer Centre",
        "Centre for Common Instrumentation Facility (CCIF), Govt. College for Women Thiruvananthapuram",
        "Kerala Government project Performance Linked Encouragement for Academic Studies (PLEASE)",
        "Chancellors Award Grant, Kerala, India",
        "Kerala State Coucil for Science Technology and Environment",
        "Kerala state plan project",
        ],

"Department of Health and Family Welfare":
        ["MoHFW","Family Welfare, New Delhi, India",'AIIMS',
        "All-India Institute of Medical Sciences",'All India Institute of Medical Sciences',
        "All India Institute of Medical Science",
        "Ministry of Health and Family Welfare","Ministry of Health",
        "Regional Office for Health and Family Welfare",
        'All India Network Programme on Neonatal Mortality',
        "Post Graduate Institute of Medical Education and Research",
        "PGIMER","JIPMER","NIMHANS","National AIDS Control Organization",
        "National Institute of Mental Health and Neuro Sciences",
        "Chittaranjan National Cancer Institute","CNCI",
        "National Institute of Health and Family Welfare",
        "International Institute of Population Sciences",
        "International Institute for Population Sciences","IIPS",
        "Kasturba Health Society","National Institute of Biologicals",
        "Food safety and Standards Authority of India","FSSAI",
        "Indian Pharmacopoeia Commission","IHBAS","NITRD","Vallabhbhai Patel Chest Institute"
        ],

"Ministry of New and Renewable Energy":
        ["MNRE","Ministry of New and Renewable Energy",
        "Sardar Swaran Singh National Institute",
        "National Centre for Photovoltaic Research and Education",
        "NCPRE","Ministry of New-Renewable Energy, New Delhi, India",
        "Solar Energy Research Institute for India"
        ],

"Department of Chemicals and Petrochemicals":
        ["Ministry of Chemicals and Fertilizers","Ministry of Chemical and Fertilizer",
        "Department of Pharmaceuticals",'Rashtriya Chemicals and Fertilizers','RCF',
        "NIPER","Department of Chemicals and Petrochemicals","DC&P, New Delhi",
        "National Institute of Pharmaceutical Education and Research"
        ],

"Government of West Bengal":
        ["Government of West Bengal","Govt. of West Bengal",
        "Govt of West Bengal","West Bengal, India","Govt. West Bengal",
        "West Bengal Government","Acharya Prafulla Chandra College",
        "Department of Science & Biotechnology, Govt. of W.B., India",
        "West Bengal Pollution Control Board, Kolkata, India",
        "Burdwan Raj College","Dept. of Science & Biotechnology, Govt. of W.B., India",
        "Department of Science, Technology and Biotechnology, West Bengal, India",
        "Department of Higher Education, Science & Technology and Biotechnology",
        "SVMCM","Swami Vivekananda Merit-cum-Means","Swami Vivekananda Merit Cum Means",
        "Swami Vivekananda Fellowship","West Bengal State Government",
        "Centre for Science, Kolkata","Department of Health and Family Welfare, West Bengal",
        "Departments of Health and Family Welfare, West Bengal",
        ],

"Government of Karnataka":
        ["Government of Karnataka","Govt. of Karnataka",
        "VGST","Govt of Karnataka, India","Karnataka Science and Technology Promotion",
        "Institute of Bioinformatics and Applied Biotechnology","Forest Department of Karnataka",
        "Department of Higher Education, Science, Technology and Bio-Technology (DHESTBT)",
        "All India Network Project on Agricultural Acarology","Directorate of Minorities"
        ],

}
